# Generated by Django 6.0.5 on 2026-06-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalpost',
            options={'ordering': ['-event_date', '-created_at']},
        ),
    ]
