# Generated by Django 6.0.5 on 2026-06-07 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalpostlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalpost',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='journal_images/'),
        ),
        migrations.AddField(
            model_name='journalpost',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='journal_videos/'),
        ),
        migrations.CreateModel(
            name='JournalPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='journal.journalpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
