# Generated by Django 6.0.5 on 2026-06-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journalpost_author_journalpost_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
