# Generated by Django 6.0.5 on 2026-06-21 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_journalpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10, verbose_name='Type de média')),
                ('file', models.FileField(blank=True, null=True, upload_to='journal_gallery/', verbose_name='Fichier')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Lien URL Externe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='journal.journalpost', verbose_name='Publication')),
            ],
            options={
                'verbose_name': 'Média de publication',
                'verbose_name_plural': 'Médias de publication',
                'ordering': ['created_at'],
            },
        ),
    ]
