# Generated by Django 6.0.5 on 2026-06-27 02:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_journalpostmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpost',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name="Image d'illustration"),
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Capsule vidéo'),
        ),
        migrations.AlterField(
            model_name='journalpostmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fichier Média'),
        ),
    ]
