# Generated by Django 6.0.5 on 2026-06-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_options_alter_skill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
