# Generated by Django 6.0.5 on 2026-06-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
