# Generated by Django 6.0.5 on 2026-06-16 22:36

import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_current_company_profile_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[profiles.validators._validate_cv]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/', validators=[profiles.validators._validate_image]),
        ),
    ]
