# Generated by Django 6.0.5 on 2026-06-22 00:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_cv_file_alter_profile_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_file',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_avatar.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
