# Generated by Django 6.0.5 on 2026-06-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.skill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('employed', 'En activité'), ('student', 'Étudiant'), ('unavailable', 'Non disponible')], default='available', max_length=20),
        ),
    ]
