# Generated by Django 6.0.5 on 2026-06-28 02:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_skills_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
