# Generated by Django 6.0.5 on 2026-05-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=180)),
                ('recruiter_name', models.CharField(max_length=140)),
                ('recruiter_phone', models.CharField(max_length=30)),
                ('recruiter_email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('contract_type', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('internship', 'Stage'), ('mission', 'Mission'), ('apprenticeship', 'Apprentissage'), ('other', 'Autre')], default='mission', max_length=30)),
                ('required_skills', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
