# Generated by Django 6.0.5 on 2026-06-05 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joboffer_options'),
        ('profiles', '0002_alter_profile_options_alter_skill_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('job_offer', 'profile'), name='unique_job_application')],
            },
        ),
    ]
