# Generated by Django 6.0.5 on 2026-06-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='job_videos/'),
        ),
    ]
