# Generated by Django 6.0.5 on 2026-06-29 20:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_joboffer_image_file_joboffer_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name="Image de l'offre"),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name="Vidéo de l'offre"),
        ),
    ]
